# Basic
title: JianMing
subtitle: JianMing的博客
welcome_message: <a>只有热爱，才会不顾一切的走下去</a>
description: 游戏玩家，技术爱好者，有点宅
creator: <a href="http://blog.nuanxinyun.com">@JianMing</a>

url: "http://blog.nuanxinyun.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 暖心云记账, description: 简单易用的记账应用，网站和APP同步数据, url: 'http://nuanxinyun.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
#    weibo: onevcat
    github: jianming348
#    twitter: onevcat
#    gplus: 107108267983477358170
    mail: jianming348@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
